// 画像生成用の英語プロンプト（開発時だけ使う。アプリ本体には含めない）
// メニュー名(日本語) → 料理の英語表現
export const MENU_EN: Record<string, string> = {
  星空しょうゆラーメン: 'soy sauce ramen in a bowl with egg, pork slices and green onion',
  濃厚みそラーメン: 'miso ramen with corn and butter',
  月見とんこつ: 'tonkotsu ramen with a raw egg yolk',
  つけ麺: 'tsukemen dipping noodles with a broth bowl',
  チャーシュー丼: 'chashu pork rice bowl',
  '餃子（6個）': 'pan fried gyoza dumplings on a plate',
  から揚げ: 'japanese fried chicken karaage',
  ウーロン茶: 'glass of iced oolong tea',
  'まぐろ握り（2貫）': 'two tuna nigiri sushi',
  'サーモン握り（2貫）': 'two salmon nigiri sushi',
  'えび握り（2貫）': 'two shrimp nigiri sushi',
  特上おまかせ10貫: 'premium assorted sushi platter of ten pieces',
  サーモン丼: 'salmon sashimi rice bowl',
  鉄火巻: 'tekka maki tuna roll sushi',
  茶碗蒸し: 'chawanmushi steamed egg custard in a cup',
  あおさ味噌汁: 'miso soup in a bowl',
  ポンポコバーガー: 'hamburger with lettuce and tomato',
  ダブルチーズバーガー: 'double cheeseburger',
  てりやきチキンバーガー: 'teriyaki chicken burger',
  フィッシュバーガー: 'fish fillet burger',
  フライドポテト: 'french fries in a paper box',
  'ナゲット（8個）': 'chicken nuggets',
  コーラ: 'cola in a glass with ice',
  バニラシェイク: 'vanilla milkshake',
  マルゲリータ: 'margherita pizza',
  クワトロフォルマッジ: 'four cheese pizza',
  ペパロニ: 'pepperoni pizza',
  シーフードミックス: 'seafood pizza',
  シーザーサラダ: 'caesar salad',
  ガーリックブレッド: 'garlic bread',
  ジェラート: 'gelato in a cup',
  ジンジャーエール: 'ginger ale in a glass',
  森のバターチキンカレー: 'butter chicken curry with rice',
  ほうれん草キーマ: 'spinach keema curry with rice',
  野菜たっぷりカレー: 'vegetable curry with rice',
  スパイスポークカレー: 'pork curry with rice',
  'ナン（2枚）': 'naan bread',
  サモサ: 'samosa',
  ラッシー: 'lassi in a glass',
  チャイ: 'masala chai tea in a cup',
  ブレンドコーヒー: 'cup of black coffee',
  カフェラテ: 'cafe latte with latte art',
  抹茶ラテ: 'matcha latte',
  ミルクティー: 'milk tea in a glass',
  ホットサンド: 'toasted ham and cheese sandwich',
  たまごサンド: 'egg salad sandwich',
  ホットケーキ: 'stack of pancakes with butter and syrup',
  プリン: 'custard pudding with caramel',
  天龍チャーハン: 'fried rice in a bowl',
  麻婆豆腐定食: 'mapo tofu with rice',
  エビチリ: 'shrimp in chili sauce',
  酢豚: 'sweet and sour pork',
  '焼き餃子（8個）': 'pan fried gyoza dumplings',
  '小籠包（4個）': 'xiaolongbao soup dumplings in a steamer',
  '春巻（2本）': 'fried spring rolls',
  杏仁豆腐: 'almond tofu dessert with fruit',
  純豆腐チゲ: 'soft tofu stew sundubu jjigae in a stone pot',
  ビビンバ: 'bibimbap',
  プルコギ定食: 'bulgogi beef with rice',
  チーズタッカルビ: 'cheese dak galbi spicy chicken',
  チヂミ: 'korean pancake jeon',
  キンパ: 'kimbap rolls',
  トッポギ: 'tteokbokki spicy rice cakes',
  マッコリ風ドリンク: 'milky white drink in a bowl',
  特製牛丼: 'beef bowl gyudon',
  カツ丼: 'katsudon pork cutlet rice bowl',
  親子丼: 'oyakodon chicken and egg rice bowl',
  天丼: 'tempura rice bowl tendon',
  豚汁: 'tonjiru pork miso soup',
  お新香: 'japanese pickled vegetables',
  生卵: 'raw egg in a small dish',
  緑茶: 'cup of green tea',
  いちごショート: 'strawberry shortcake slice',
  濃厚チーズケーキ: 'cheesecake slice',
  モンブラン: 'mont blanc chestnut cake',
  季節のタルト: 'fruit tart',
  '生チョコ（6粒）': 'chocolate truffles',
  'マカロン（4個）': 'macarons',
  シュークリーム: 'cream puff',
  紅茶: 'cup of black tea',
  チキンサラダボウル: 'chicken salad bowl',
  アボカドボウル: 'avocado bowl',
  サーモンボウル: 'salmon poke bowl',
  豆腐ボウル: 'tofu salad bowl',
  スムージー: 'green smoothie in a glass',
  野菜スープ: 'vegetable soup in a bowl',
  フルーツカップ: 'fruit cup',
  ナッツバー: 'nut bar snack',
  'もも串（2本）': 'grilled chicken thigh skewers yakitori',
  'ねぎま串（2本）': 'negima yakitori chicken and leek skewers',
  'つくね串（2本）': 'tsukune chicken meatball skewers',
  '皮串（2本）': 'crispy chicken skin skewers',
  焼き鳥盛り合わせ10本: 'assorted yakitori skewers platter',
  だし巻き卵: 'japanese rolled omelette dashimaki tamago',
  冷やしトマト: 'chilled tomato',
  烏龍茶: 'glass of oolong tea',
}

// 店のジャンル → 店の写真に使う英語（卓上に並んだ料理の写真にする）
export const GENRE_EN: Record<string, string> = {
  ラーメン: 'ramen', 寿司: 'sushi', ハンバーガー: 'burgers and fries', ピザ: 'pizza', カレー: 'curry',
  カフェ: 'cafe drinks and sandwiches', 中華: 'chinese dishes', 韓国料理: 'korean dishes', 丼もの: 'japanese rice bowls',
  スイーツ: 'cakes and sweets', ヘルシー: 'healthy salad bowls', 焼き鳥: 'yakitori skewers',
}
